{"apiVersion":"v1","data":{"REACT_APP_PASSWORD":"changeMe"},"kind":"ConfigMap","metadata":{"labels":{"emco/deployment-id":"4159257416098272377-wef-5-0"},"name":"r1-ue-mngmt-tool-env-cfgmap","namespace":"default"}}
